### ISSUE TITLE
paser data error.

### ISSUE THREAD

**Issue by fireblackman** [vearne/grpcreplay#19]
如果项目是Python或者是Java的grpc服务，怎么使用grpc反射，我测试的demo是Python的，好像并不能正常使用

**Comment by vearne** [comment]
Please give me the python demo so I can try it.

**Comment by vearne** [comment]
> 如果项目是Python或者是Java的grpc服务，怎么使用grpc反射，我测试的demo是Python的，好像并不能正常使用

https://github.com/grpc/grpc-java/tree/master/examples/example-reflection

**Comment by vearne** [comment]
我专门又测试了一下，java也是没有问题的。

**Comment by vearne** [comment]
tested it again and there was no problem with python gRPC.
[python grpc demo](https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_server_with_reflection.py)
[How to use the demo](https://grpc.io/docs/languages/python/quickstart/)

**Comment by fireblackman** [comment]
Thanks, I will try it again

**Comment by fireblackman** [comment]
$ sudo ./grpcr --input-raw="127.0.0.1:50051" --output-stdout --output-grpc="grpc://127.0.0.1:50052"

   ______ ____   ____   ______ ____ 
  / ____// __ \ / __ \ / ____// __ \
 / / __ / /_/ // /_/ // /    / /_/ /
/ /_/ // _, _// ____// /___ / _, _/ 
\____//_/ |_|/_/     \____//_/ |_|   
2024/07/27 11:06:23 [info] input-raw, [127.0.0.1:50051]
2024/07/27 11:06:23 [info] input-file-directory, []
2024/07/27 11:06:23 [info] input-file-replay-speed, 1
2024/07/27 11:06:23 [info] input-rocketmq-name-server, []
2024/07/27 11:06:23 [info] input-rocketmq-topic, test
2024/07/27 11:06:23 [info] output-stdout, true
2024/07/27 11:06:23 [info] output-file-directory, []
2024/07/27 11:06:23 [info] output-grpc, [grpc://127.0.0.1:50052]
2024/07/27 11:06:23 [info] output-rocketmq-name-server, []
2024/07/27 11:06:23 [info] output-rocketmq-topic, test
2024/07/27 11:06:23 [info] create new Processer
2024/07/27 11:06:23 [info] ipSet:[fe80::8404:b0ff:fe4f:c4bc fe80::e893:62ff:fe13:1c59 192.168.40.222 fe80::594d:4f40:eed7:a59d 127.0.0.1 ::1 172.17.0.1 fe80::42:d1ff:fec3:674]
2024/07/27 11:06:23 [info] create grpc output, addr:127.0.0.1:50052
2024/07/27 11:06:23 [info] plugins:#####  len(Inputs):1, len(Outputs):2, len(All):3   #####
2024/07/27 11:06:23 [info] All history connections has exited.
2024/07/27 11:06:23 [info] listener:device:lo, port:50051, filter:tcp and port 50051
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error
2024/07/27 11:08:16 [error] netPkg error:process packet error

![image](https://github.com/user-attachments/assets/4d115a37-5497-48c4-bb01-e9fa24f79c1b)
![image](https://github.com/user-attachments/assets/625f0cc7-65ba-48c9-a4a5-5ddc9117c50c)
![image](https://github.com/user-attachments/assets/52b5f04e-a0e9-4f30-a22c-b1b0d8aceaf5)

**Comment by fireblackman** [comment]
我试了下，但是还是不能转发给另一个服务，不知道是哪里出了问题，还要麻烦指点一下

**Comment by vearne** [comment]
I have reproduced the problem, I will check it out

**Comment by vearne** [comment]
> 我试了下，但是还是不能转发给另一个服务，不知道是哪里出了问题，还要麻烦指点一下

这个问题是由于，vearne/grpcreplay 不支持IPv6导致的，请你把
greeter_server.py中
```
 server.add_insecure_port("[::]:" + port) 
改为 
 server.add_insecure_port("127.0.0.1: 50051") 
```

另外，我把代码也更新了一下，你重新更新一下，重新build一下bin文件 @fireblackman

**Comment by fireblackman** [comment]
Thanks, I have tried it again, it worked
